/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef, useLayoutEffect, useMemo } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

// Toon Rocket model (toon_rocket.glb)
const Certificate = React.memo(function ToonRocket(props) {
  const groupRef = useRef();
  // Meshes: ['Object_4', ..., 'Object_39']
  // Materials: ['0.780392_0.772549_0.780392_0.000000_0.000000', ...]
  const { nodes, materials } = useGLTF("/models/toon_rocket.glb");

  // Dynamically collect all mesh nodes and their materials
  const meshes = useMemo(
    () =>
      Object.entries(nodes)
        .filter(([, v]) => v && v.isMesh && v.geometry)
        .map(([name, mesh]) => {
          // Try to get the material name from the mesh, fallback to first material
          let matName = mesh.material?.name;
          if (!matName && mesh.material && typeof mesh.material === "string")
            matName = mesh.material;
          if (!matName) matName = Object.keys(materials)[0];
          return { name, mesh, matName };
        }),
    [nodes, materials]
  );

  // Auto scale & center horizontally, anchor bottom at y=0 then apply slight downward offset
  React.useLayoutEffect(() => {
    function updateModelLayout() {
      if (!groupRef.current || meshes.length === 0) return;
      const box = new THREE.Box3();
      meshes.forEach(({ mesh }) => box.expandByObject(mesh));
      const size = new THREE.Vector3();
      const center = new THREE.Vector3();
      box.getSize(size);
      box.getCenter(center);
      const longest = Math.max(size.x, size.y, size.z) || 1;
      // Responsive target size based on window width
      let target = 2.0;
      const width = window.innerWidth;
      if (width < 640) {
        target = 1.2; // mobile
      } else if (width < 1024) {
        target = 1.7; // tablet
      } else {
        target = 2.0; // desktop
      }
      const s = target / longest;
      groupRef.current.scale.set(s, s, s);
      const bottomY = box.min.y;
      // Responsive offsets
      let yOffset, xOffset;
      if (width < 640) {
        yOffset = -1.2; // mobile
        xOffset = 0;
      } else if (width < 1024) {
        yOffset = -1.7; // tablet
        xOffset = 0
      } else {
        yOffset = 2; // desktop
        xOffset = -5.5;
      }
      groupRef.current.position.set(
        -center.x * s + xOffset,
        -bottomY * s + yOffset,
        -center.z * s
      );
      // Rotate model to stand vertically and point upward (rocket orientation)
      groupRef.current.rotation.set(-Math.PI / 2, 0, 0);
    }
    updateModelLayout();
    window.addEventListener("resize", updateModelLayout);
    return () => window.removeEventListener("resize", updateModelLayout);
  }, [meshes]);

  // Subtle rotation + very gentle lateral drift for "orbital" feel
  useFrame((state) => {
    if (!groupRef.current) return;
    const t = state.clock.getElapsedTime();
    groupRef.current.rotation.z = t * 0.5; // slow spin
    // mild sinusoidal sway (no vertical): x & z micro movement
    const swayAmp = 0.05;
    groupRef.current.position.x += Math.sin(t * 0.2) * swayAmp * 0.002;
    groupRef.current.position.z += Math.cos(t * 0.25) * swayAmp * 0.002;
  });

  return (
    <group ref={groupRef} dispose={null} {...props}>
      {meshes.map(({ name, mesh, matName }) => {
        // Assign correct material by dynamic name
        let material = materials[matName] || mesh.material;
        // Optional: clone material to tweak emissive without global side-effects
        if (material && !material._toonRocketCloned) {
          const cloned = material.clone();
          cloned._toonRocketCloned = true;
          // Subtle glow for main body, more for yellow, less for dark
          if (cloned.emissive) {
            cloned.emissiveIntensity = 0.15;
            cloned.emissive = new THREE.Color(0x888899);
          }
          material = cloned;
        }
        return (
          <mesh
            key={name}
            geometry={mesh.geometry}
            material={material}
            castShadow
            receiveShadow
            name={name}
          />
        );
      })}
    </group>
  );
});

export default Certificate;
useGLTF.preload("/models/toon_rocket.glb");
