/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef, useLayoutEffect, useMemo } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

// Space Station variant of Staff component
const Experience = React.memo(function SpaceStation(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/models/outhere_space_buddy.glb");

  // Collect all mesh nodes dynamically (robust to naming changes)
  const meshes = useMemo(
    () =>
      Object.entries(nodes)
        .filter(([, v]) => v && v.isMesh && v.geometry)
        .map(([name, mesh]) => ({ name, mesh })),
    [nodes]
  );

  // Auto scale & center horizontally, anchor bottom at y=0 then apply slight downward offset
  React.useLayoutEffect(() => {
    function updateModelLayout() {
      if (!groupRef.current || meshes.length === 0) return;
      const box = new THREE.Box3();
      meshes.forEach(({ mesh }) => box.expandByObject(mesh));
      const size = new THREE.Vector3();
      const center = new THREE.Vector3();
      box.getSize(size);
      box.getCenter(center);
      const longest = Math.max(size.x, size.y, size.z) || 1;
      // Responsive target size based on window width
      let target = 2.0;
      const width = window.innerWidth;
      if (width < 640) {
        target = 1.2; // mobile
      } else if (width < 1024) {
        target = 1.7; // tablet
      } else {
        target = 1.8; // desktop
      }
      const s = target / longest;
      groupRef.current.scale.set(s, s, s);
      // Responsive offsets
      let yOffset, xOffset;
      if (width < 640) {
        yOffset = -1.2; // mobile
        xOffset = 0.2;
      } else if (width < 1024) {
        yOffset = -1.7; // tablet
        xOffset = 0.5;
      } else {
        yOffset = -2; // desktop
        xOffset = -5;
      }
      // (Removed old xOffset for responsive version)
      const bottomY = box.min.y;
      groupRef.current.position.set(
        -center.x * s + xOffset,
        -bottomY * s + yOffset,
        -center.z * s
      );
    }
    updateModelLayout();
    window.addEventListener("resize", updateModelLayout);
    return () => window.removeEventListener("resize", updateModelLayout);
  }, [meshes]);

  // Subtle rotation + very gentle lateral drift for "orbital" feel
  useFrame((state) => {
    if (!groupRef.current) return;
    const t = state.clock.getElapsedTime();
    groupRef.current.rotation.y = t * 0.5; // slow spin
    // mild sinusoidal sway (no vertical): x & z micro movement
    const swayAmp = 0.05;
    groupRef.current.position.x += Math.sin(t * 0.2) * swayAmp * 0.002;
    groupRef.current.position.z += Math.cos(t * 0.25) * swayAmp * 0.002;
  });

  return (
    <group ref={groupRef} dispose={null} {...props}>
      {meshes.map(({ name, mesh }) => {
        let material = mesh.material;
        if (!material && mesh.material?.name && materials[mesh.material.name]) {
          material = materials[mesh.material.name];
        }
        // Optional: clone material to tweak emissive without global side-effects
        if (material && !material._spaceStationCloned) {
          const cloned = material.clone();
          cloned._spaceStationCloned = true;
          // Light touch emissive so station "glows" subtly
          if (cloned.emissive) {
            cloned.emissiveIntensity = 0.4;
            cloned.emissive = new THREE.Color(0x224466);
          }
          material = cloned;
        }
        return (
          <mesh
            key={name}
            geometry={mesh.geometry}
            material={material}
            castShadow
            receiveShadow
            name={name}
          />
        );
      })}
    </group>
  );
});

export default Experience;
useGLTF.preload("/models/outhere_space_buddy.glb");
