/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef, useMemo, useLayoutEffect } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HatModel = React.memo(function UFOModel(props) {
  const { nodes, materials } = useGLTF("/models/ufo.glb");
  const groupRef = useRef();

  const lightMaterialNames = [
    "LightRing",
    "InnerBulbs",
    "OuterBulb",
    "Beam",
    "Inside",
  ]; // candidates for emissive glow

  // Gather mesh nodes
  const meshes = useMemo(
    () =>
      Object.entries(nodes)
        .filter(([, v]) => v && v.isMesh && v.geometry)
        .map(([name, mesh]) => ({ name, mesh })),
    [nodes]
  );

  // Center & scale UFO
  useLayoutEffect(() => {
    if (!groupRef.current || meshes.length === 0) return;
    const box = new THREE.Box3();
    meshes.forEach(({ mesh }) => box.expandByObject(mesh));
    const size = new THREE.Vector3();
    const center = new THREE.Vector3();
    box.getSize(size);
    box.getCenter(center);
    const longest = Math.max(size.x, size.y, size.z) || 1;
    const target = 3.5; // desired normalized size for UFO
    const s = target / longest;
    groupRef.current.scale.set(s, s, s);
    groupRef.current.position.set(-center.x * s, -center.y * s, -center.z * s);
  }, [meshes]);

  // Animation: slow spin + gentle hover + slight circular drift
  useFrame((state) => {
    if (!groupRef.current) return;
    const t = state.clock.getElapsedTime();
    const baseY = 0.6; // raised base offset
    groupRef.current.rotation.y = t * 0.4; // spin
    groupRef.current.position.y = baseY + Math.sin(t * 1.3) * 0.07; // raised hover
    groupRef.current.position.x += Math.sin(t * 0.2) * 0.0008; // subtle drift accumulation
    groupRef.current.position.z += Math.cos(t * 0.2) * 0.0008;
  });

  return (
    <group ref={groupRef} dispose={null} {...props}>
      {meshes.map(({ name, mesh }) => {
        let material = mesh.material;
        if (!material && mesh.material?.name && materials[mesh.material.name]) {
          material = materials[mesh.material.name];
        }
        // Clone to adjust emissive for light parts without mutating original globally
        if (material && lightMaterialNames.includes(material.name || "")) {
          material = material.clone();
          material.emissive = new THREE.Color(0.3, 0.6, 1.0);
          material.emissiveIntensity = 0.9;
        }
        return (
          <mesh
            key={name}
            geometry={mesh.geometry}
            material={material}
            castShadow
            receiveShadow
            name={name}
          />
        );
      })}
    </group>
  );
});

export default HatModel;
useGLTF.preload("/models/ufo.glb");
