/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef, useMemo, useLayoutEffect } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

// Re-purpose Wizard component to load space.glb
const Wizard = React.memo(function SpaceModel(props) {
  const { nodes, materials } = useGLTF("/models/space.glb");
  const groupRef = useRef();

  // Collect mesh nodes
  const meshes = useMemo(
    () =>
      Object.entries(nodes)
        .filter(([, v]) => v && v.isMesh && v.geometry)
        .map(([name, mesh]) => ({ name, mesh })),
    [nodes]
  );

  // Center and normalize scale (increase target size for larger presence)
  useLayoutEffect(() => {
    if (!groupRef.current || meshes.length === 0) return;
    const box = new THREE.Box3();
    meshes.forEach(({ mesh }) => box.expandByObject(mesh));
    const size = new THREE.Vector3();
    const center = new THREE.Vector3();
    box.getSize(size);
    box.getCenter(center);
    const longest = Math.max(size.x, size.y, size.z) || 1;
    const target = 3.5; // increased desired size
    const s = target / longest;
    groupRef.current.scale.set(s, s, s);
    groupRef.current.position.set(-center.x * s, -center.y * s, -center.z * s);
  }, [meshes]);

  useFrame((state) => {
    if (!groupRef.current) return;
    const t = state.clock.getElapsedTime();
    // Continuous slow spin facing front: assume model's front is along +Z; adjust base offset if needed
    const baseFacingOffset = 0; // change to Math.PI/2 etc. if orientation still off
    groupRef.current.rotation.y = baseFacingOffset + t * 0.25; // continuous spin
    groupRef.current.position.y = -0.2 + Math.sin(t * 1.2) * 0.08; // slightly larger hover
  });

  return (
    <group ref={groupRef} dispose={null} {...props}>
      {meshes.map(({ name, mesh }) => {
        // Attempt more robust material resolution (some meshes may share materials array indices)
        let material = mesh.material;
        if (!material && mesh.material?.name && materials[mesh.material.name]) {
          material = materials[mesh.material.name];
        }
        return (
          <mesh
            key={name}
            geometry={mesh.geometry}
            material={material}
            castShadow
            receiveShadow
            name={name}
          />
        );
      })}
    </group>
  );
});

export default Wizard;
useGLTF.preload("/models/space.glb");
